# Generated by Django 4.2.7 on 2026-08-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='category',
            field=models.CharField(choices=[('D', 'Drug'), ('F', 'Food'), ('E', 'Environment'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies_set', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='patientallergy',
            unique_together={('patient', 'allergy')},
        ),
    ]
