# Generated by Django 6.1 on 2026-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_alter_encounter_patient'),
        ('core', '0004_add_staff_head_role'),
        ('prescriptions', '0002_alter_prescription_encounter_related_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['encounter'], name='prescriptio_encount_b9eab3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_940ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_by', 'prescribed_at'], name='prescriptio_prescri_8df50a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription'], name='prescriptio_prescri_d670da_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['medicine'], name='prescriptio_medicin_79533a_idx'),
        ),
    ]
