# Generated by Django 6.1 on 2026-08-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_radiologyorder_encounter_and_more'),
        ('prescriptions', '0003_prescription_prescriptio_encount_b9eab3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.encounter'),
        ),
    ]
