# Generated by Django 4.2.7 on 2026-07-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('treatment_plan', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['icd10_code'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Completed'), ('X', 'Cancelled')], default='O', max_length=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'permissions': [('can_start_encounter', 'Can start a new clinical encounter'), ('can_complete_encounter', 'Can complete/close a clinical encounter'), ('can_view_any_encounter', 'Can view encounters of any patient')],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('systolic_pressure', models.PositiveSmallIntegerField()),
                ('diastolic_pressure', models.PositiveSmallIntegerField()),
                ('pulse_rate', models.PositiveSmallIntegerField()),
                ('respiratory_rate', models.PositiveSmallIntegerField()),
                ('oxygen_saturation', models.PositiveSmallIntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinical.encounter')),
            ],
        ),
    ]
