# Generated by Django 4.2.7 on 2026-07-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_department_appointment_doctor_and_more'),
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.staff'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.staff'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.staff'),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(help_text='Name of the disease, surgery, or vaccine', max_length=255)),
                ('icd10_code', models.CharField(blank=True, max_length=10, verbose_name='ICD-10 Code')),
                ('condition_type', models.CharField(choices=[('CH', 'Chronic Disease'), ('AC', 'Acute Illness'), ('SU', 'Surgical Procedure'), ('MH', 'Mental Health'), ('FH', 'Family History'), ('IM', 'Immunization'), ('OT', 'Other')], default='OT', max_length=2)),
                ('status', models.CharField(choices=[('A', 'Active'), ('R', 'Resolved / Administered'), ('M', 'Managed / Controlled')], default='A', max_length=1)),
                ('onset_date', models.DateField(blank=True, help_text='Date of diagnosis, surgery, or administration', null=True)),
                ('resolution_date', models.DateField(blank=True, help_text='Date resolved (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Details about family member, vaccine lot, etc.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
            ],
            options={
                'verbose_name': 'Medical History',
                'verbose_name_plural': 'Medical Histories',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
