# Generated by Django 4.2.7 on 2026-07-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_diagnosis_diagnosed_by_diagnosis_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='discharge_summary',
            field=models.TextField(blank=True),
        ),
    ]
