# Generated by Django 4.2.7 on 2026-07-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_profile_photo'),
        ('patients', '0002_alter_patient_user'),
        ('clinical', '0003_encounter_discharge_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent to Radiology'), ('R', 'Results Received'), ('X', 'Cancelled')], default='P', max_length=1)),
                ('clinical_notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ris_order_id', models.CharField(blank=True, help_text='ID from the RIS', max_length=100)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='radiology_results/')),
                ('result_text', models.TextField(blank=True, help_text='Structured result text from RIS')),
                ('result_received_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_orders', to='clinical.encounter')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.radiologytest')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
