# Generated by Django 4.2.7 on 2026-08-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_radiologytest_radiologyorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['order', 'icd10_code'], 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='certainty',
            field=models.CharField(choices=[('C', 'Confirmed'), ('P', 'Presumed')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diag_status',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Ruled Out')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='order',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.encounter'),
        ),
    ]
