# Generated by Django 4.2.7 on 2026-08-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
        ('clinical', '0005_alter_diagnosis_options_diagnosis_certainty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
    ]
