# Generated by Django 6.1 on 2026-08-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_alter_encounter_patient'),
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyorder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radiology_orders', to='clinical.encounter'),
        ),
        migrations.AlterField(
            model_name='radiologyorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
    ]
