# Generated by Django 6.1 on 2026-08-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_radiologyorder_encounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='clinical.encounter'),
        ),
    ]
