[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = .
norecursedirs = node_modules .git .venv venv env static media results
addopts = --cov=. --cov-report=term-missing --cov-report=html