# Generated by Django 4.2.7 on 2026-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('I', 'Checked In'), ('C', 'Completed'), ('X', 'Cancelled'), ('N', 'No Show')], default='S', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'permissions': [('can_reschedule_appointment', 'Can reschedule an appointment to a new date/time'), ('can_transfer_appointment', 'Can transfer an appointment to a different doctor'), ('can_cancel_appointment', 'Can cancel a scheduled appointment'), ('can_assign_doctor', 'Can assign or reassign a doctor to an appointment'), ('can_view_all_appointments', 'Can view appointments of all patients across departments'), ('can_checkin_patient', 'Can mark a patient as checked-in for their appointment')],
            },
        ),
    ]
