# Generated by Django 4.2.7 on 2026-08-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
        ('appointments', '0003_appointment_appointment_schedul_7069dc_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_at'], 'permissions': [('can_reschedule_appointment', 'Can reschedule an appointment to a new date/time'), ('can_transfer_appointment', 'Can transfer an appointment to a different doctor'), ('can_cancel_appointment', 'Can cancel a scheduled appointment'), ('can_assign_doctor', 'Can assign or reassign a doctor to an appointment'), ('can_view_all_appointments', 'Can view appointments of all patients across departments'), ('can_checkin_patient', 'Can mark a patient as checked-in for their appointment'), ('can_triage_patient', 'Can perform triage assessment')]},
        ),
        migrations.AddField(
            model_name='appointment',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='triage_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 - Immediate (Life-threatening)'), (2, 'Level 2 - Emergent (< 15 min)'), (3, 'Level 3 - Urgent (< 60 min)'), (4, 'Level 4 - Semi-urgent (< 120 min)'), (5, 'Level 5 - Non-urgent (< 240 min)')], help_text='ESI Triage Level (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='triage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='triage_nurse',
            field=models.ForeignKey(blank=True, help_text='Nurse assigned for initial triage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_appointments', to='core.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('I', 'Checked In'), ('G', 'Triaged'), ('C', 'Completed'), ('X', 'Cancelled'), ('N', 'No Show')], default='S', max_length=1),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['triage_nurse', 'status'], name='appointment_triage__1c75e5_idx'),
        ),
    ]
