# Generated by Django 6.1 on 2026-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_triage_vitals'),
        ('core', '0004_add_staff_head_role'),
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'scheduled_at'], name='appointment_doctor__2f3cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['department'], name='appointment_departm_485db0_idx'),
        ),
    ]
