# Generated by Django 4.2.7 on 2026-08-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_user_role'),
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
        ('clinical', '0005_alter_diagnosis_options_diagnosis_certainty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent to Lab'), ('R', 'Results Received'), ('X', 'Cancelled')], default='P', max_length=1)),
                ('clinical_notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lms_order_id', models.CharField(blank=True, help_text='ID from the LMS', max_length=100)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('result_text', models.TextField(blank=True, help_text='Structured result text from LMS')),
                ('result_received_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='clinical.encounter')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_ordered', to='core.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.labtest')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
