# Generated by Django 4.2.7 on 2026-08-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_staff_head_role'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Physician who verified the results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_orders', to='core.staff'),
        ),
    ]
