# Generated by Django 6.1 on 2026-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_alter_encounter_patient'),
        ('core', '0004_add_staff_head_role'),
        ('laboratory', '0002_laborder_is_verified_laborder_verified_at_and_more'),
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'status'], name='laboratory__patient_a022a2_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['encounter', 'ordered_at'], name='laboratory__encount_28c20d_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'ordered_at'], name='laboratory__status_ce2264_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordered_by', 'ordered_at'], name='laboratory__ordered_1deac7_idx'),
        ),
    ]
