# Generated by Django 6.1 on 2026-08-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_radiologyorder_encounter_and_more'),
        ('laboratory', '0003_laborder_laboratory__patient_a022a2_idx_and_more'),
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='clinical.encounter'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
    ]
