# Generated by Django 4.2.7 on 2026-07-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0003_encounter_discharge_summary'),
        ('patients', '0002_alter_patient_user'),
        ('core', '0002_staff_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('lab_report', 'Lab Report'), ('radiology_image', 'Radiology Image'), ('referral_letter', 'Referral Letter'), ('consent_form', 'Consent Form'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clinical.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.staff')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
