# Generated by Django 4.2.7 on 2026-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician'), ('patient', 'Patient'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
