# Generated by Django 4.2.7 on 2026-08-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_allergy_category_patientallergy_notes_and_more'),
        ('core', '0003_alter_user_role'),
        ('appointments', '0003_appointment_appointment_schedul_7069dc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 - Immediate (Life-threatening)'), (2, 'Level 2 - Emergent (< 15 min)'), (3, 'Level 3 - Urgent (< 60 min)'), (4, 'Level 4 - Semi-urgent (< 120 min)'), (5, 'Level 5 - Non-urgent (< 240 min)')], help_text='ESI Triage Acuity Level', null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('triage_notes', models.TextField(blank=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('W', 'Waiting for Triage'), ('T', 'In Triage'), ('G', 'Triaged - Waiting for Doctor'), ('A', 'Assigned to Doctor'), ('P', 'In Consultation'), ('C', 'Completed'), ('L', 'Left Without Being Seen'), ('F', 'Transferred')], default='W', max_length=1)),
                ('is_fast_track', models.BooleanField(default=False, help_text='Minor injuries/illnesses that can be seen quickly')),
                ('assigned_room', models.CharField(blank=True, max_length=20)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('triage_started_at', models.DateTimeField(blank=True, null=True)),
                ('triage_completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_wait_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_wait_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100)),
                ('left_reason', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='appointments.appointment')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queue_patients', to='core.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='patients.patient')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_patients', to='core.staff')),
            ],
            options={
                'verbose_name': 'Patient Queue',
                'verbose_name_plural': 'Patient Queues',
                'ordering': ['triage_level', 'arrival_time'],
                'permissions': [('can_triage_patient', 'Can perform triage assessment'), ('can_assign_doctor', 'Can assign patient to a doctor'), ('can_manage_queue', 'Can manage the entire queue'), ('can_view_queue_dashboard', 'Can view the queue dashboard')],
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('W', 'Waiting for Triage'), ('T', 'In Triage'), ('G', 'Triaged - Waiting for Doctor'), ('A', 'Assigned to Doctor'), ('P', 'In Consultation'), ('C', 'Completed'), ('L', 'Left Without Being Seen'), ('F', 'Transferred')], max_length=1, null=True)),
                ('to_status', models.CharField(choices=[('W', 'Waiting for Triage'), ('T', 'In Triage'), ('G', 'Triaged - Waiting for Doctor'), ('A', 'Assigned to Doctor'), ('P', 'In Consultation'), ('C', 'Completed'), ('L', 'Left Without Being Seen'), ('F', 'Transferred')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='queue_management.patientqueue')),
            ],
            options={
                'verbose_name': 'Queue Event',
                'verbose_name_plural': 'Queue Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientqueue',
            index=models.Index(fields=['triage_level', 'arrival_time'], name='queue_manag_triage__66a5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientqueue',
            index=models.Index(fields=['current_status', 'triage_level'], name='queue_manag_current_352557_idx'),
        ),
        migrations.AddIndex(
            model_name='patientqueue',
            index=models.Index(fields=['assigned_doctor', 'current_status'], name='queue_manag_assigne_b56df6_idx'),
        ),
        migrations.AddIndex(
            model_name='patientqueue',
            index=models.Index(fields=['patient', '-arrival_time'], name='queue_manag_patient_9a5b01_idx'),
        ),
    ]
